### ISSUE TITLE
[EPIC] Hosting Services

### ISSUE THREAD

**Issue by LanceGundersen** [Team-SquidBear/agilebear-frontend#1]
## Description
We need to identify hosting providers for the various aspects of the web application to include the frontend, backend functions and database services.

## Initiative / goal
Set up the tooling for future development efforts to include code hosting on GitHub, frontend hosting, backend functions and database services.

### Hypothesis
This should be relatively simple to set up once the hosting providers are identified. Success will be measured by pull requests being merged to the main branch and triggering a build on the hosting platform.

## Acceptance criteria and must have scope
- [ ] GitHub Repository Setup
- [ ] Frontend host identified and test code pushed
- [ ] Functions host identified and test code pushed
- [ ] Database host identified and test code pushed

## Stakeholders
Everyone

## Timeline
What's the timeline for this Epic, what resources are needed, and what might potentially block this from hitting the projected end date.
This shouldn't take very long to do but could be delayed if a service fails criteria initially thought to be available on the free tier, etc.
