### ISSUE TITLE
ITA

### ISSUE THREAD

**Issue by ChuckSenior** [Team-SquidBear/agilebear-frontend#16]
Sum of performance traits divided by 9
![Screen Shot 2021-05-31 at 22 32 33](https://user-images.githubusercontent.com/82341546/120258499-28144c80-c260-11eb-82b7-d06497acc24b.png)

## Issue Description
-Calculate ITA based on established logic. 
-Sum of graded traits divided by total number of traits present
-Acceptable numbers are 1-9
-ignore zeros

---
## Tasks
- [ ] Create end point
- [ ] Return a number

## Acceptance Criteria
- [ ] Only possible returns; 1.00- 9.00 in the below combinations
- [ ] Numbers should be 1 whole digit followed by two decimals (1.00, 2.11 etc)
- [ ] ***Double check round up or round down***

![Screen Shot 2021-05-31 at 23 17 35](https://user-images.githubusercontent.com/82341546/120261696-6dd41380-c266-11eb-8aa6-8522723c3a06.png)
---
