### ISSUE TITLE
GitHub Setup

### ISSUE THREAD

**Issue by LanceGundersen** [Team-SquidBear/agilebear-frontend#2]
## Issue Description
Setup the GitHub Organization and repository.

## Tasks
- [x] Setup GitHub Organization
- [x] Setup GitHub Repositories
- [x] Setup ZenHub Integration
- [ ] Create Initial Epics
- [ ] Create Initial Issues

## Acceptance Criteria
- [ ] GitHub Setup
- [ ] ZenHub Integration
