### ISSUE TITLE
#1355201209 Summary Group Average (SGA) Calculation

### ISSUE THREAD

**Issue by LanceGundersen** [Team-SquidBear/agilebear-frontend#22]
Write a function that calculates Summary Group Average (SGA)
![Screen Shot 2021-05-31 at 22 32 33](https://user-images.githubusercontent.com/82341546/120258499-28144c80-c260-11eb-82b7-d06497acc24b.png)

#1355201209

## Issue Description
Given a valid number for an ITA and a valid number of sailors in the summary group, calculate and return the sum

example `14.42 / 3 = 4.81`

---
## Tasks
- [ ] Create end point
- [ ] Return a number

## Acceptance Criteria
- [ ] Numbers should be 1 whole digit followed by two decimals (1.00, 2.11 etc)
- [ ] ***Double check round up or round down***
---
