### ISSUE TITLE
Individual Trait Average (ITA) Calculation

### ISSUE THREAD

**Issue by LanceGundersen** [Team-SquidBear/agilebear-frontend#23]
Sum of performance traits divided by 9
![Screen Shot 2021-05-31 at 22 32 33](https://user-images.githubusercontent.com/82341546/120258499-28144c80-c260-11eb-82b7-d06497acc24b.png)

## Issue Description
-Calculate ITA based on established logic. 
-Sum of graded traits divided by total number of traits present
-Acceptable numbers are 1-9
-ignore zeros

---
## Tasks
- [ ] Create end point
- [ ] Return a number

## Acceptance Criteria
- [ ] Only possible returns; 1.00- 9.00 in the below combinations
- [ ] Numbers should be 1 whole digit followed by two decimals (1.00, 2.11 etc)
- [ ] ***Double check round up or round down***

![Screen Shot 2021-05-31 at 23 17 35](https://user-images.githubusercontent.com/82341546/120261696-6dd41380-c266-11eb-8aa6-8522723c3a06.png)
---

Full ITA results ***FOR REFERENCE***
1
1.111111111
1.222222222
1.333333333
1.444444444
1.555555556
1.666666667
1.777777778
1.888888889
2
2.111111111
2.222222222
2.333333333
2.444444444
2.555555556
2.666666667
2.777777778
2.888888889
3
3.111111111
3.222222222
3.333333333
3.444444444
3.555555556
3.666666667
3.777777778
3.888888889
4
4.111111111
4.222222222
4.333333333
4.444444444
4.555555556
4.666666667
4.777777778
4.888888889
5
5.111111111
5.222222222
5.333333333
5.444444444
5.555555556
5.666666667
5.777777778
5.888888889
6
6.111111111
6.222222222
6.333333333
6.444444444
6.555555556
6.666666667
6.777777778
6.888888889
7
7.111111111
7.222222222
7.333333333
7.444444444
7.555555556
7.666666667
7.777777778
7.888888889
8
8.111111111
8.222222222
8.333333333
8.444444444
8.555555556
8.666666667
8.777777778
8.888888889
9
