### ISSUE TITLE
Research Hosting of Identified Services

### ISSUE THREAD

**Issue by LanceGundersen** [Team-SquidBear/agilebear-frontend#3]
## Issue Description
We need to identify hosts for the three critical services of frontend hosting, functions and a database.

All services should be free and well enough known to reduce friction for a fast go to market strategy. The ability to build from pushed to the main branch would be a nice perk.

## Tasks
- [ ] Identify a frontend hosting platform
- [ ] Identify a functions hosting platform
- [ ] Identify a database hosting platform

## Acceptance Criteria
- [ ] Full stack identified and limitations documented
