### ISSUE TITLE
Setup Frontend Web Hosting

### ISSUE THREAD

**Issue by LanceGundersen** [Team-SquidBear/agilebear-frontend#4]
## Issue Description
Based on discovery findings, setup frontend code in order to familiarize with the platform and as a proof-of-concept.

## Tasks
- [ ] Web hosting is procured
- [ ] Push code to host

## Acceptance Criteria
- [ ] Web host is accessible via web address
