### ISSUE TITLE
Setup Database Hosting

### ISSUE THREAD

**Issue by LanceGundersen** [Team-SquidBear/agilebear-frontend#5]
## Issue Description
Based on discovery findings, setup database code in order to familiarize with the platform and as a proof-of-concept.

## Tasks
- [ ] Database hosting is procured
- [ ] Push arbitrary data to host

## Acceptance Criteria
- [ ] Database host is accessible e.g. via Postman call
