### ISSUE TITLE
Setup Functions

### ISSUE THREAD

**Issue by LanceGundersen** [Team-SquidBear/agilebear-frontend#6]
## Issue Description
Based on discovery findings, setup functions code in order to familiarize with the platform and as a proof-of-concept.

## Tasks
- [ ] Function hosting is procured
- [ ] Create arbitrary function

## Acceptance Criteria
- [ ] Function call is accessible via hosts documentation
