### ISSUE TITLE
Setup Hosts Crosstalk

### ISSUE THREAD

**Issue by LanceGundersen** [Team-SquidBear/agilebear-frontend#7]
## Issue Description
Tie all services together to familiarize with the platform and as a proof-of-concept. An example should include calls to the database from the front-end host a function call and saving data back to the database.

## Tasks
- [ ] Read arbitrary data from the database
- [ ] Create a server side function to update database
- [ ] Saves data to the database

## Acceptance Criteria
- [ ] Frontend reads data from database
- [ ] Action on frontend triggers a server side function and updates data in the database
- [ ] Frontend saves data to the database
